FROM python:3.10.19

WORKDIR /opt/app

RUN apt-get update \
     && apt-get install -y procps curl redis-tools \
     && rm -rf /var/lib/apt/lists/*

COPY ./app/pyproject.toml pyproject.toml

RUN pip install --upgrade pip \
      && pip install --no-cache-dir poetry==1.8.3 \
     && poetry config virtualenvs.create false \
     && poetry install --no-interaction --no-ansi --no-root

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./app .

RUN chmod +x ./main.py

RUN groupadd -r app_group \
     && useradd -d /opt/app -r -g app_group app \
     && chown app:app_group -R /opt/app/ \
     && chown app:app_group -R /var/log/

USER app

# Wait for services to be ready before running tests
CMD ["sh", "-c", "curl -f http://test_elastic_search:9200/_cluster/health && redis-cli -h test_redis ping && pytest tests/ -v"]